### ISSUE TITLE
antd  里面怎么用？

### ISSUE THREAD

**Issue by MinHongwei** [hanzhangyu/rc-print#4]
这个是启动 antd的错误   
./node_modules/rc-print/src/index.js
Module parse failed: Unexpected token (21:21)
You may need an appropriate loader to handle this file type.
|
| export default class Print extends React.Component {
|     static propTypes = {
|         insertHead: PropTypes.bool, // 是否植入本页面的head标签
|         ignoreHeadJs: PropTypes.bool, // 当insertHead启用时是否屏蔽JS文件

dome1 的代码 
import React, { Component } from 'react';
import Print from 'rc-print/src';

export default class Demo1 extends Component {
  constructor() {
    super();
    this.state = {
      text: 'page',
    };
  }

  render() {
    const { text } = this.state;
    return (
      <div>
        <h3>
        This is Demo1&nbsp;&nbsp;<a href="https://github.com/hanzhangyu/rc-print/blob/master/demo/Demo1.js">code</a>
        </h3>
        Open Iframe and inset Head which has wrapped the css file`s link to print something. <br />
        <button
          onClick={() => { document.getElementById('test').test.onPrint(); }}
        >print
        </button>
        <Print id="test" title="this is Demo1`s title">
          <div>
            <p className="red">first {text}</p>
            <button
              onClick={() => {
                                this.setState({ text: text === 'page' ? 'updated page' : 'page' });
                            }}
            >update print content
            </button>
            <p className="green">second {text}</p>
            <p className="pink">third {text}</p>
          </div>
        </Print>
      </div>
    );
  }
}

**Comment by MinHongwei** [comment]
`import React, { Component } from 'react';
import Print from 'rc-print/src';

export default class Demo1 extends Component {
  constructor() {
    super();
    this.state = {
      text: 'page',
    };
  }

  render() {
    const { text } = this.state;
    return (
      <div>
        <h3>
        This is Demo1&nbsp;&nbsp;<a href="https://github.com/hanzhangyu/rc-print/blob/master/demo/Demo1.js">code</a>
        </h3>
        Open Iframe and inset Head which has wrapped the css file`s link to print something. <br />
        <button
          onClick={() => { document.getElementById('test').test.onPrint(); }}
        >print
        </button>
        <Print id="test" title="this is Demo1`s title">
          <div>
            <p className="red">first {text}</p>
            <button
              onClick={() => {
                                this.setState({ text: text === 'page' ? 'updated page' : 'page' });
                            }}
            >update print content
            </button>
            <p className="green">second {text}</p>
            <p className="pink">third {text}</p>
          </div>
        </Print>
      </div>
    );
  }
}
`

**Comment by hanzhangyu** [comment]
You need `transform-class-properties` babel plugin.
PLZ  install `babel-plugin-transform-class-properties` first.

~~By the way, how do you use this in you code. The main of `rq-print` is `lib/index.js`~~. Opps, I see it
