### ISSUE TITLE
控制台  大量的警告

### ISSUE THREAD

**Issue by MinHongwei** [hanzhangyu/rc-print#6]
webpack-internal:///115:33 Warning: React does not recognize the `clearIframeCache` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `cleariframecache` instead. If you accidentally passed it from a parent component, remove it from the DOM element. --类似这个的很多
webpack-internal:///115:33 Warning: Unknown event handler property `onStart`. It will be ignored.  还有一个onEnd的

**Comment by hanzhangyu** [comment]
Show your code. PLZ

**Comment by MinHongwei** [comment]
import React, { Component } from 'react';
import Print from 'rc-print/lib';
import { Button, Card } from 'antd';
import styles from './index.less';

export default class Demo1 extends Component {
  render() {
    return (
      <div>
        <h3>This is Demo&nbsp;&nbsp;<a href="#">code</a></h3>
            Open a new window and don`t inset Head to print something. <br />
        <button
          onClick={() => {
                    this.refs.test.onPrint();
                }}
        >print
        </button>
        <Print
          ref="test"
          // isIframe={false}
          insertHead={false}
          title="this is Demo`s title"
        >
          <div>
            <img src="http://www.xunqiandu.com/images/img-3.jpg" alt="imgTest" />
            <p><font color="red">first line, we don`t have color</font></p>
            <p color="green">second line, I have bigger font-size in the print`s
                        review page because of media query
            </p>
            <p style={{ textDecoration: 'underline' }}>third line, I have underline but my
                        underline is come from inline style
            </p>
          </div>
        </Print>
      </div>
    );
  }
}

**Comment by MinHongwei** [comment]
就是用的demo1,2 在测试， 用的阿里公司的antd dev等

**Comment by MinHongwei** [comment]
我准备去 把 你的源吗改了用  而不是做为插件来用，如果你还在不想兼容性的发布。 另外 想确认是按照警告改了就可以了，用批量替换不影响吗。

**Comment by MinHongwei** [comment]
Warning: React does not recognize the `bodyStyle` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `bodystyle` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Demo1)
    in Print (created by Demo1)
    in div (created by Demo1)
    in Demo1 (created by DynamicComponent)
    in DynamicComponent (created by Route)
    in Route (created by BasicLayout)
    in Switch (created by BasicLayout)
    in div (created by BasicLayout)
    in div (created by Basic)
    in Basic (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by ContainerQuery)
    in ContainerQuery (created by BasicLayout)
    in DocumentTitle (created by SideEffect(DocumentTitle))
    in SideEffect(DocumentTitle) (created by BasicLayout)
    in BasicLayout (created by Connect(BasicLayout))
    in Connect(BasicLayout) (created by DynamicComponent)
    in DynamicComponent (created by Route)
    in Route
    in Switch
    in Router
    in LocaleProvider
    in Provider
    in Unknown

**Comment by MinHongwei** [comment]
Warning: React does not recognize the `insertHead` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inserthead` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Demo1)
    in Print (created by Demo1)
    in div (created by Demo1)
    in Demo1 (created by DynamicComponent)
    in DynamicComponent (created by Route)
    in Route (created by BasicLayout)
    in Switch (created by BasicLayout)
    in div (created by BasicLayout)
    in div (created by Basic)
    in Basic (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by ContainerQuery)
    in ContainerQuery (created by BasicLayout)
    in DocumentTitle (created by SideEffect(DocumentTitle))
    in SideEffect(DocumentTitle) (created by BasicLayout)
    in BasicLayout (created by Connect(BasicLayout))
    in Connect(BasicLayout) (created by DynamicComponent)
    in DynamicComponent (created by Route)
    in Route
    in Switch
    in Router
    in LocaleProvider
    in Provider
    in Unknown
printWarning @ warning.js?6327:33
warning @ warning.js?6327:57
validateProperty$1 @ react-dom.development.js?cada:13546
warnUnknownProperties @ react-dom.development.js?cada:13580
validateProperties$2 @ react-dom.development.js?cada:13600
validatePropertiesInDevelopment @ react-dom.development.js?cada:13639
setInitialProperties$1 @ react-dom.development.js?cada:13906
finalizeInitialChildren @ react-dom.development.js?cada:14989
completeWork @ react-dom.development.js?cada:8648
completeUnitOfWork @ react-dom.development.js?cada:10132
performUnitOfWork @ react-dom.development.js?cada:10234
workLoop @ react-dom.development.js?cada:10288
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
renderRoot @ react-dom.development.js?cada:10366
performWorkOnRoot @ react-dom.development.js?cada:11014
performWork @ react-dom.development.js?cada:10967
requestWork @ react-dom.development.js?cada:10878
scheduleWorkImpl @ react-dom.development.js?cada:10732
scheduleWork @ react-dom.development.js?cada:10689
enqueueSetState @ react-dom.development.js?cada:6212
Component.setState @ react.development.js?99ee:237
(anonymous) @ dynamic.js?9a9f:99
Promise.then (async)
load @ dynamic.js?9a9f:96
DynamicComponent @ dynamic.js?9a9f:82
constructClassInstance @ react-dom.development.js?cada:6355
updateClassComponent @ react-dom.development.js?cada:7839
beginWork @ react-dom.development.js?cada:8225
performUnitOfWork @ react-dom.development.js?cada:10224
workLoop @ react-dom.development.js?cada:10288
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
renderRoot @ react-dom.development.js?cada:10366
performWorkOnRoot @ react-dom.development.js?cada:11014
performWork @ react-dom.development.js?cada:10967
requestWork @ react-dom.development.js?cada:10878
scheduleWorkImpl @ react-dom.development.js?cada:10732
scheduleWork @ react-dom.development.js?cada:10689
enqueueSetState @ react-dom.development.js?cada:6212
Component.setState @ react.development.js?99ee:237
(anonymous) @ dynamic.js?9a9f:99
Promise.then (async)
load @ dynamic.js?9a9f:96
DynamicComponent @ dynamic.js?9a9f:82
constructClassInstance @ react-dom.development.js?cada:6355
updateClassComponent @ react-dom.development.js?cada:7839
beginWork @ react-dom.development.js?cada:8225
performUnitOfWork @ react-dom.development.js?cada:10224
workLoop @ react-dom.development.js?cada:10288
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
renderRoot @ react-dom.development.js?cada:10366
performWorkOnRoot @ react-dom.development.js?cada:11014
performWork @ react-dom.development.js?cada:10967
requestWork @ react-dom.development.js?cada:10878
scheduleWorkImpl @ react-dom.development.js?cada:10732
scheduleWork @ react-dom.development.js?cada:10689
scheduleTopLevelUpdate @ react-dom.development.js?cada:11193
updateContainer @ react-dom.development.js?cada:11231
(anonymous) @ react-dom.development.js?cada:15226
unbatchedUpdates @ react-dom.development.js?cada:11102
renderSubtreeIntoContainer @ react-dom.development.js?cada:15225
render @ react-dom.development.js?cada:15290
render @ index.js?4380:126
start @ index.js?4380:68
(anonymous) @ index.js?1fdf:24
(anonymous) @ index.js:3686
__webpack_require__ @ index.js:708
fn @ index.js:113
(anonymous) @ index.js:3342
__webpack_require__ @ index.js:708
(anonymous) @ index.js:806
(anonymous) @ index.js:809
warning.js?6327:33 Warning: React does not recognize the `ignoreHeadJs` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ignoreheadjs` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Demo1)
    in Print (created by Demo1)
    in div (created by Demo1)
    in Demo1 (created by DynamicComponent)
    in DynamicComponent (created by Route)
    in Route (created by BasicLayout)
    in Switch (created by BasicLayout)
    in div (created by BasicLayout)
    in div (created by Basic)
    in Basic (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by ContainerQuery)
    in ContainerQuery (created by BasicLayout)
    in DocumentTitle (created by SideEffect(DocumentTitle))
    in SideEffect(DocumentTitle) (created by BasicLayout)
    in BasicLayout (created by Connect(BasicLayout))
    in Connect(BasicLayout) (created by DynamicComponent)
    in DynamicComponent (created by Route)
    in Route
    in Switch
    in Router
    in LocaleProvider
    in Provider
    in Unknown

**Comment by hanzhangyu** [comment]
按照错误的提示是说你把`insertHead`等props放在了原始的node上面，而且你给我看的code很奇怪，像是与MD语法冲突了。可以的话，请在codepen或者其他网站上复现，这样我才能给予帮助，谢谢啦。

**Comment by MinHongwei** [comment]
import React, { Component } from 'react';
import Print from 'rc-print/lib';
import { Button, Card } from 'antd';
import styles from './index.less';

export default class Demo1 extends Component {
  render() {
    return (
      <div>
        <h3>This is Demo&nbsp;&nbsp;<a href="#">code</a></h3>
            Open a new window and don`t inset Head to print something. <br />
        <Button
          onClick={() => {
                    this.refs.test.onPrint();
                }}
        >print
        </Button>
        <Print
          ref="test"
          // isIframe={false}
          insertHead={false}
          title="this is Demo`s title"
        >
          <div>
            <img src="http://www.xunqiandu.com/images/img-3.jpg" alt="imgTest" />
            <p><font color="red">first line, we don`t have color</font></p>
            <p color="green">second line, I have bigger font-size in the print`s
                        review page because of media query
            </p>
            <p style={{ textDecoration: 'underline' }}>third line, I have underline but my
                        underline is come from inline style
            </p>
            <Card>
              <div style={{ border: '2px solid #a1a1a1', padding: '10px 40px', width: '300px', borderRadius: '25px' }}>div，版测试</div>
              <table className={styles.insptable} width="710px" align="center">
                <tbody>
                  <tr style={{ border: '0px' }} className={styles.tr1}>
                    <td colSpan="18" style={{ textAlign: 'center' }}>
                      <p style={{ fontSize: '14.0pt', fontFamily: '微软雅黑' }}>
                        <strong>在用汽车自由加速试验（滤纸烟度法）检测报告</strong>
                      </p>
                    </td>
                    <td colSpan="7"><img width="187" height="46" id="barcode" src="" alt="" align="right" /></td>
                  </tr>
                  <tr>
                    <td colSpan="10" style={{ paddingBottom: '5px', textAlign: 'left', paddingLeft: '0px' }}>检测报告编号:<span id="testno" /></td>
                    <td colSpan="8" style={{ paddingBottom: '5px', paddingLeft: '0px' }}>检测时间:<span id="testtime" /></td>
                    <td colSpan="7" style={{ paddingBottom: '5px', paddingLeft: '0px' }}>下次检验时间:&nbsp;&nbsp;<span id="testvalidto" /></td>
                  </tr>
                  <tr>
                    <td
                      colSpan="25"
                      className={styles.td31}
                      style={{ paddingTop: '5px', borderRight: '#000000 1px solid', borderLeft: '#000000 1px solid', borderTop: '#000000 1px solid' }}
                    ><strong>1.车主信息</strong>
                    </td>
                  </tr>
                  <tr className={styles.tr4}>
                    <td colSpan="4" style={{ borderLeft: '#000000 1px solid' }}>车主/单位:</td>
                    <td colSpan="21" style={{ borderRight: '#000000 1px solid' }}><span id="ownername" /></td>
                  </tr>
                  <tr className={styles.tr5}>
                    <td colSpan="4" style={{ paddingBottom: '5px', borderLeft: '#000000 1px solid' }}>联系电话:</td>
                    <td colSpan="5" style={{ paddingBottom: '5px' }}><span id="ownertelno" /></td>
                    <td colSpan="3" style={{ paddingBottom: '5px' }}>联系地址:</td>
                    <td colSpan="13" style={{ paddingBottom: '5px', borderRight: '#000000 1px solid' }}><span id="owneraddress" /></td>
                  </tr>
                  <tr className={styles.tr6} style={{ height: '20px' }}>
                    <td colSpan="4" style={{ paddingTop: '5px', borderLeft: '#000000 1px solid', borderTop: '#000000 1px solid' }}><strong>2.车辆信息</strong></td>
                    <td style={{ paddingTop: '5px', borderTop: '#000000 1px solid' }}>&nbsp;</td>
                    <td colSpan="8" style={{ paddingTop: '5px', borderTop: '#000000 1px solid' }}><i>外检单号  :&nbsp;&nbsp;<span id="appearancecode" /></i></td>
                    <td colSpan="12" style={{ paddingTop: '5px', borderRight: '#000000 1px solid', borderTop: '#000000 1px solid' }}>&nbsp;</td>
                  </tr>
                  <tr style={{ height: '10px' }}><td colSpan="25" style={{ borderRight: '#000000 1px solid' }} /></tr>
                  <tr className={styles.tr9} style={{ fontSize: '14px', fontWeight: 'bold', height: '30px' }}>
                    <td colSpan="4" style={{ borderLeft: '#000000 1px solid' }}>车牌号码  :</td>
                    <td colSpan="6" ><span id="plateno" /></td>
                    <td />
                    <td colSpan="4" >车辆识别码  :</td>
                    <td colSpan="10"><span id="vin" /></td>
                  </tr>
                </tbody>
              </table>
            </Card>
          </div>
        </Print>
      </div>
    );
  }
}

**Comment by MinHongwei** [comment]
https://codesandbox.io/s/v85405vml0

**Comment by MinHongwei** [comment]
在阿里的 https://ant.design/index-cn  基础上使用。

**Comment by hanzhangyu** [comment]
好的，我等会看下

**Comment by hanzhangyu** [comment]
https://github.com/hanzhangyu/rc-print/blob/9dce34a643952e6565d0b6efa9eb8f66b850bc5c/src/index.js#L208-L211

I have fixed it, THX.
