### ISSUE TITLE
单页面中的使用问题

### ISSUE THREAD

**Issue by MinHongwei** [hanzhangyu/rc-print#7]
操作方式，。.进入不打印的页面 ->进入打印的页面，点击打印按钮，正常打印。  然后 在点其他的菜单之后。再次点入刚刚的打印页面  无法正常打印。
![qq 20180228152148](https://user-images.githubusercontent.com/34823990/36775018-3acffc52-1c9b-11e8-9773-85d8ff1168b6.png)
![qq 20180228152154](https://user-images.githubusercontent.com/34823990/36775019-3b418084-1c9b-11e8-8161-423fd3b006ae.png)

重新加载 刷新后好用，是不是 react的生命周期 导致的，我在使用的过程中，需要设置生命周期吗。

**Comment by hanzhangyu** [comment]
进入其他页面之后这个打印页面是卸载了的吗？

https://github.com/hanzhangyu/rc-print/blob/master/lib/index.js#L117

调试一下这里面的iframe是什么

**Comment by MinHongwei** [comment]
这个可以通过开启  isIframe={false}  弹出一股页面来打印，  但是  我设置在css文件中的样式。你的这个插件有提供引用方式吗?    <Print
            ref="test"
            isIframe={false}
            bodyStyle
            insertHead={false}
>  是把bodyStyle 改为真吗 ？   还是用你在demo3  或者md文件中描述的方式

**Comment by MinHongwei** [comment]
如这个table表css定义的  边线

**Comment by MinHongwei** [comment]
![qq 20180228170450](https://user-images.githubusercontent.com/34823990/36779090-c43b9dda-1ca9-11e8-9048-ed40ae392a35.png)

**Comment by hanzhangyu** [comment]
`bodyStyle`会把body里面的style标签复制进去，而一般来说CSS文件都是在head里面的，所以insertHead默认就是为true

**Comment by hanzhangyu** [comment]
I will fix this bug by the `iframe` way.

**Comment by hanzhangyu** [comment]
I had fixed in the new version `1.0.4`
